addons:
  sonarcloud:
    organization: "jonknet"
    token:
      secure: "YwHReOauOymA1pSBmdBFzfO8zFhA+BBubmObpQrne9pAyC8TSUQDir/6AynW2wp6z03QCYoZrPN1ZfAB8K5TCJOWwSMPYCPp38iRNT5rDWXttiSMglI/S+2eLyihB/mtHDd+7O/NpYntwvBJKgtwC0scVhWA1T6zAe9Ts6v6l7SaGJCCzv4FpfTxdUKRN8AniJgyY2wWtbxA864KpqhMYhrpMbJJ2HEnAyEOvkPFlQP0ef8HYdXxptsYno664DkRSiqggjD6S6AN5r6BGbB0xRUeSkE6Anf+lWHkrKirGywfhi4KuMpzaKvGIEsHj6sTuvkMZGnUCbE9DGOUZfO4kqKRm8w7kNE66P42Sa3EjU0QnmY20l+s1Q+rqimWhLjzlKqlO12Es7dYit6UXlNPjzv2kG1hnBCaYJLEF7q0CRtFNqm07R1KDAKHw/MoviFFbsaF2Ni0kTXmHrpRm9LrZi/coDpzDVT2Lj8cxk2Zj7weY/4/yAfpp+Se99m4EBLAr+AIAEH4HXS6ptolLMJ4M/zlVgyqn2hKfpX4o/Ci2k/MX8dYSBehXOq1SdpK/nyUEqxRuxCAZQnGFEbldyEz4L1yRWJMB5e72BQxz5+zm8ZnItkdOOkAVXWVbjdq3pwhchBS9jDOsYEaZojNWiZoi+baiPsmX70YTPEW+ZLesKg=" # encrypted value of your token

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output <your clean build command>
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

