addons:
  sonarcloud:
    organization: jonknet
script:
- build-wrapper-linux-x86-64 --out-dir bw-output <your clean build command>
- sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.user=382245ab514e64d56037386e8ccd9aebfa83cece
env:
  global:
    secure: UZAj7ye99yZ0EHnBjRbywGRPjOTwQFTjOWfZxbiaGrbiBMJNWkC5e7nOKoTVh/AIMZhemkziJfhvrSjt6BC1taPgH8pbdZ7EinhamT8W8yIyG5Xqw0db9sg69jvrY1ERG4DAEw+tRlKxMSDlrNT2L3Rd/WnhX0LUkAB8/YP0G1JqlMNPnoaYB3CEgNXyVyu6PgMztovQPsqsEVbWhwx+l9gd9tmeugYYDkNg8mfO2+NPcep4ZDyj8Sql+e4rbtvPL7ray4bM5vovTfjyvIxZ18gusN+dg2iAFSp7uwWZ5LDBa3ID8eKPUTPDNNh68TWqgr4Ljm4XrykJZ5acjs3kpp+cdgqYx7ynnsjbRF/IvNvj+9C0Hl5LDaGZGfLhP5XG8M2e9pg5Y2v1KrZCysmiXhjIMHD5OFqXlGd3uwxANA+cCusEJ3eozaK4Btf5D8T3ro8koKAB8+BccQDR4Sg1F8JtjTZAicsSo+PxRehcvPtXXGx9n9YRMZ5vhWNE1KOGfeTHVbkHe3LkVv/L4wcX59QRhbrAlCcDw3/ZqmxgXR4Pn3YkG3VgKNnEny0yzJEp13Wyp6YMp1q0JEr0x3A9l+ij540AcQtO56mCqc9/qwVCjr/VA4lTAY4/78v0lfInb9p/ESjwLT2AUi0Tc7MLwC41mWlfWzjl96/e67Lx13I=
